project:
  type: book
  output-dir: docs

book:
  title: "Guide de classification du mesozooplancton en Mer Ligurienne"

  author:
    - name: "Guyliann Engels"
      url: "https://github.com/GuyliannEngels"
      affiliation: "Service d'écologie numérique, Université de Mons, Belgique"
      affiliation-url: "https://github.com/EcoNum"
    - name: "Philippe Grosjean"
      url: "https://github.com/phgrosjean"
      affiliation: "Service d'écologie numérique, Université de Mons, Belgique"
      affiliation-url: "https://github.com/EcoNum"
  date: now
  chapters:
    - index.qmd
    - intro.qmd
    - "01plankton_crustacea.qmd"
    - "02plankton_dark.qmd"
    - "03plankton_gelatinous.qmd"
    - "04plankton_small.qmd"
    - "05alter.qmd"
    - references.qmd

bibliography: references.bib

before_chapter_script: 'R/init.R'

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

lang: fr

editor: visual

