project:
  type: book
  output-dir: docs

book:
  title: "Identification guide of mesozooplanktonic organisms in the Ligurian Sea"
  repo-url: "https://github.com/EcoNum/zooimage_mesozooplankton_guide3"
  cover-image: "images/EcoNum-logo.png"
  author:
    - name: "Guyliann Engels"
      url: "https://github.com/GuyliannEngels"
      affiliation: "Numerical Ecology Unit, University of Mons, Belgium"
      affiliation-url: "https://github.com/EcoNum"
    - name: "Philippe Grosjean"
      url: "https://github.com/phgrosjean"
      affiliation: "Numerical Ecology Unit, University of Mons, Belgium"
      affiliation-url: "https://github.com/EcoNum"
  date: now
  chapters:
    - index.qmd
    - zooplankton_sampling.qmd
    - classification.qmd
    - n1.qmd
    - n2.qmd
    - part: n3.qmd
      chapters:
        - "01plankton_crustacea.qmd"
        - "02plankton_dark.qmd"
        - "03plankton_gelatinous.qmd"
        - "04plankton_small.qmd"
        - "05alter.qmd"
    - references.qmd

bibliography: references.bib

before_chapter_script: 'R/init.R'

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

lang: en

editor: visual

